"""empty message

Revision ID: 43fbbbf718d6
Revises: 2205ee69a118
Create Date: 2017-06-10 18:43:22.261606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43fbbbf718d6'
down_revision = '2205ee69a118'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search_counter', sa.Column('count_per_session', sa.Integer(), nullable=True))
    op.drop_column('search_counter', 'session_count')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search_counter', sa.Column('session_count', sa.INTEGER(), nullable=True))
    op.drop_column('search_counter', 'count_per_session')
    # ### end Alembic commands ###
