"""empty message

Revision ID: c5c09e3f50b4
Revises: 
Create Date: 2017-06-03 11:52:35.038161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5c09e3f50b4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('search_counter')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_counter',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('result_id', sa.INTEGER(), nullable=True),
    sa.Column('counter', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['result_id'], ['search_result.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
